openapi: 3.1.0
x-stoplight:
  id: sd31rpwjhifog
info:
  title: Car Wash API
  version: '1.3.1'
  description: Car Wash API
servers:
  - url: 'https://mxp-public-wash-api.dev.icadsistemi.com/v1'
    description: Development
  - url: 'https://mxp-public-wash-api.prod.icadsistemi.com/v1'
    description: Production
paths:
  /configuration:
    get:
      summary: Get base configuration
      tags:
        - configuration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
            application/xml:
              schema:
                type: object
                properties: {}
          headers: {}
      operationId: get-configuration
      description: 'Get the handled IINs, fuelcoupons and card codes'
  /transaction/card:
    post:
      summary: Create a new transaction with card
      operationId: post-transaction-card
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction-output'
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      description: 'Create a new car wash transaction with all cards, icad card (end of month, rechargeable) and gt cards (DKV, UTA ecc..)'
      tags:
        - transaction
  /transaction/fuelcoupon:
    parameters: []
    post:
      summary: 'Create a new transaction with fuel coupons [Details To be define]'
      operationId: post-transaction-fuelcoupon
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      tags:
        - transaction
  /transaction/loyalty/points:
    post:
      summary: 'Create a new transaction with point card [Details To be define]'
      operationId: post-transaction-loyalty-points
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      description: Register a transaction made with a point card.
      tags:
        - transaction
  /discount: {}
components:
  schemas:
    Configuration:
      type: object
      x-examples:
        Example 1:
          iin:
            - '700557'
            - '704310'
          fuel_coupons:
            - '123456'
          cards_code:
            - type: Finemese
              code: '4'
      examples:
        - cards:
            - iin: '700557'
              tag: ICAD
            - iin: '704310'
              tag: DKV
          fuel_coupons:
            - '9900'
          icad_cards_info:
            - type: Sconto
              code: '1'
              pin_required: false
            - type: Finemese
              code: '2'
              pin_required: true
            - type: Ricaricabile
              code: '3'
              pin_required: true
            - type: Raccolta punti
              code: '4'
              pin_required: false
      description: Configuration output model
      properties:
        cards:
          type: array
          description: First six digits of a supported card PAN.
          items:
            type: object
            properties:
              iin:
                type: string
                description: 'Represent the card pan prefix, different for each card owner. The same card owner could have more than 1 iin'
              tag:
                type: string
                description: |-
                  Represent the card owner tag:
                  - Icad's Cards: "ICAD"
                  - DKV's Cards: "DKV"
                  - UTA's Cards: "UTA"
            required:
              - iin
              - tag
        fuel_coupons:
          type: array
          description: ICAD Sistemi's fuel coupon prefix.
          items:
            type: string
        icad_cards_info:
          type: array
          description: 7th digit of an ICAD Sistemi card.
          items:
            type: object
            properties:
              type:
                type: string
                description: Card type name
              code:
                type: string
                description: Card type code
              pin_required:
                type: boolean
                description: Indicate if the PIN is required or not for the related card
            required:
              - type
              - code
              - pin_required
      required:
        - cards
        - icad_cards_info
    Transaction:
      title: Transaction input
      x-stoplight:
        id: 9ff7e72a42a3a
      type: object
      x-tags:
        - transaction
      examples:
        - card: string
          amount: 0
          date_time: '2019-08-24T14:15:22'
          is_code: string
          transaction_details:
            - unit_price: 0
              amount: 0
              quantity: 0
              article_code: string
          transaction_id: 0
          terminal_id: string
          card_pin: string
      properties:
        card:
          type: string
          description: Card track 2.
        amount:
          type: number
          description: Total transaction amount
        date_time:
          type: string
          format: date-time
          description: Transaction datetime
        is_code:
          type: string
          description: Station IS Code
        transaction_details:
          type: array
          description: |
            Transaction details
          items:
            type: object
            properties:
              unit_price:
                type: number
                format: float
                description: Washing unite price
              amount:
                type: number
                format: float
                description: |
                  Washing amount
              quantity:
                type: integer
                description: |
                  Washing quantity
              article_code:
                type: string
                description: Washing article code
            required:
              - unit_price
              - amount
              - quantity
              - article_code
        transaction_id:
          type: number
          description: Transaction identifier
        terminal_id:
          type: string
          description: Terminal identifier
        card_pin:
          type: string
          description: PIN AES encrypted. Present only for cards requiring it
        label_key:
          type: string
          x-stoplight:
            id: bj97u6fbw10od
      required:
        - card
        - amount
        - date_time
        - is_code
        - transaction_details
        - transaction_id
        - terminal_id
    Transaction-output:
      title: Transaction-output
      x-stoplight:
        id: 3gyieyipn3myk
      type: object
      properties:
        action_code:
          type: string
          description: |-
            Operation result code:
            - "000": Success
            - "001": Card disabled
            - "002": Card not found
            - "004": Not enough credit on card
            - "005": Expired Card
            - "006": Card Type not found
            - "007": No articles availables
            - "008": Not enough residual on card
            - "009": Disabled customer
            - "012": Disabled customer on this station
            - "013": Circuit card is not enabled on this station
            - "014": Incorrect PIN
            - "015": Generic error
            - "904": Format error
        transaction_id:
          type: number
          description: Echoed transaction identifier
        card_balance:
          type: number
          format: float
          description: 'Remaining credit, only for rechargeable cards.'
        approval_code:
          type: string
          description: Assigned to successful transactions
        vehicle_plate:
          type: string
          description: Optional vehicle plate.
      required:
        - action_code
        - transaction_id
  securitySchemes:
    CognitoDevelopment:
      type: oauth2
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: 'https://dub-dev-icadsistemi-users.auth.eu-west-1.amazoncognito.com/token'
      description: ''
    CognitoProduction:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://dub-prod-icadsistemi-users.auth.eu-west-1.amazoncognito.com/token'
          scopes: {}
x-internal: false
security:
  - Cognito production: []
  - Cognito development: []
